name: publish

# Based on https://github.com/UoMMScRobotics/SFR_ROS2/blob/main/.github/workflows/main.yml
on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ubuntu_dev  

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-24.04-arm', 'ubuntu-latest']  
    runs-on: ${{ matrix.os }}      

    steps:
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
       
          - name: Build and push ubuntu_dev amd64
            if: matrix.os == 'ubuntu-latest'
            id: push_amd64
            uses: docker/build-push-action@v6
            with:
              platforms: linux/amd64
              push: true
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64
              
          - name: Build and push ubuntu_dev arm64
            if: matrix.os == 'ubuntu-24.04-arm'
            id: push_arm64
            uses: docker/build-push-action@v6
            with:
              platforms: linux/arm64
              push: true
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64    
