name: publish

# Based on https://github.com/UoMMScRobotics/SFR_ROS2/blob/main/.github/workflows/main.yml
on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ubuntu_dev  

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-24.04-arm', 'ubuntu-latest']  
    runs-on: ${{ matrix.os }}      

    steps:
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
            with:
              driver: docker
       
          - name: Build and save ubuntu_dev amd64
            if: matrix.os == 'ubuntu-latest'
            id: build_amd64
            run: |
             docker build -t ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64 images/ubuntu_dev/
             docker save ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64 -o ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-amd64.tar

          - name: Upload amd64 image
            if: matrix.os == 'ubuntu-latest'
            id: upload_amd64
            uses: actions/upload-artifact@v4
            with:
              name: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64
              path: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-amd64.tar 

          - name: Build and save ubuntu_dev arm64
            if: matrix.os == 'ubuntu-24.04-arm'
            id: build_arm64
            run: |
             docker build -t ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64 images/ubuntu_dev/
             docker save ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64 -o /tmp/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-arm64.tar

          - name: Upload arm64 image
            if: matrix.os == 'ubuntu-24.04-arm'
            id: upload_arm64
            uses: actions/upload-artifact@v4
            with:
              name: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64
              path: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-arm64.tar 
          




   

              
