name: publish

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
          - uses: actions/checkout@v2
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
       
          - name: Build and push ubuntu_dev
            uses: docker/build-push-action@v6
            with:
              platforms: linux/amd64 #,linux/arm64
              push: true
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/ubuntu_dev
