name: publish

# Based on https://github.com/UoMMScRobotics/SFR_ROS2/blob/main/.github/workflows/main.yml
on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ubuntu_dev  

jobs:
  build-and-upload-artifact-image:
    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-24.04-arm', 'ubuntu-latest']  #'ubuntu-24.04-arm', 
    runs-on: ${{ matrix.os }}      

    steps:          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
            with:
              driver: docker-container

          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Create output folder
            run: mkdir -p output  

          - name: Build ubuntu_dev [AMD64]
            if: matrix.os == 'ubuntu-latest'
            id: build_amd64
            uses: docker/build-push-action@v6
            with:
              push: False
              context: images/ubuntu_dev/
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64
              outputs: type=docker, dest=${{ env.IMAGE_NAME }}-amd64.tar
           
          - name: Upload artifact [AMD64]
            if: matrix.os == 'ubuntu-latest'
            id: upload_amd64
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.IMAGE_NAME }}-amd64
              path: ${{ env.IMAGE_NAME }}-amd64.tar 
              retention-days:  1

          - name: Build ubuntu_dev [ARM64]
            if: matrix.os == 'ubuntu-24.04-arm'
            id: build_arm64
            uses: docker/build-push-action@v6
            with:
              push: False
              context: images/ubuntu_dev/
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64
              outputs: type=docker, dest=${{ env.IMAGE_NAME }}-arm64.tar
           
          - name: Upload artifact [ARM64]
            if: matrix.os == 'ubuntu-24.04-arm'
            id: upload_arm64
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.IMAGE_NAME }}-arm64
              path: ${{ env.IMAGE_NAME }}-arm64.tar 
              retention-days:  1     




          




   

              
