name: publish

# Based on https://github.com/UoMMScRobotics/SFR_ROS2/blob/main/.github/workflows/main.yml
on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: ubuntu_dev  

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
          os: ['ubuntu-latest']  #'ubuntu-24.04-arm', 
    runs-on: ${{ matrix.os }}      

    steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Create output folder
            run: mkdir -p output
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
             username: ${{ vars.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3    
            with:
              driver: docker

          - name: Build and save ubuntu_dev amd64
            if: matrix.os ==  'ubuntu-latest'
            id: build_amd64
            uses: docker/build-push-action@v6
            with:
              push: False
              file: images/ubuntu_dev/Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64
              outputs: type=docker, dest=./output/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-amd64.tar

          - name: Upload amd64 image
            if: matrix.os == 'ubuntu-latest'
            id: upload_amd64
            uses: actions/upload-artifact@v4
            with:
              name: ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:amd64
              path: ./output/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}-amd64.tar 
              retention-days:  1


          




   

              
